import useImage from 'use-image';
import useTheme from './useTheme';

const useImageData = () => {
  const { theme } = useTheme();
  const [mainBg] = useImage(theme.urls.worldMainBg);

  const imageList = [
    {
      src: theme.urls.worldPortal,
      x: 715,
      y: 525,
      originWidth: 32,
      originHeight: 32,
      width: 70,
      height: 70,
      animateType: 1,
    },
    // {
    //   src: theme.urls.worldDummy1,
    //   x: 120,
    //   y: 175,
    //   originWidth: 342,
    //   originHeight: 126,
    //   width: 342,
    //   height: 126,
    //   animateType: 0,
    // },
    // {
    //   src: theme.urls.worldDummy2,
    //   x: 850,
    //   y: 525,
    //   originWidth: 342,
    //   originHeight: 126,
    //   width: 342,
    //   height: 126,
    //   animateType: 0,
    // },
    // {
    //   src: theme.urls.worldDummy3,
    //   x: 1070,
    //   y: 155,
    //   originWidth: 342,
    //   originHeight: 126,
    //   width: 342,
    //   height: 126,
    //   animateType: 0,
    // },
    // {
    //   src: theme.urls.worldDummy4,
    //   x: 275,
    //   y: 545,
    //   originWidth: 342,
    //   originHeight: 126,
    //   width: 342,
    //   height: 126,
    //   animateType: 0,
    // },
    {
      src: theme.urls.worldDummyArrow,
      x: 694,
      y: 410,
      originWidth: 42,
      originHeight: 80,
      width: 42,
      height: 80,
      animateType: 2,
    },
  ];

  const spriteList = [
    {
      src: theme.urls.worldSprite1,
      x: 600,
      y: 265,
      frame: 4,
      originWidth: 96,
      originHeight: 64,
      width: 154,
      height: 102,
    },
    {
      src: theme.urls.worldSprite4,
      x: 803,
      y: 288,
      frame: 4,
      originWidth: 66,
      originHeight: 130,
      width: 108,
      height: 212,
    },
    {
      src: theme.urls.worldSprite2,
      x: 644,
      y: 472,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 747,
      y: 472,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 644,
      y: 524,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 747,
      y: 524,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 1050,
      y: 475,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 1110,
      y: 475,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 439,
      y: 324,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },
    {
      src: theme.urls.worldSprite2,
      x: 517,
      y: 324,
      frame: 6,
      originWidth: 32,
      originHeight: 32,
      width: 40,
      height: 40,
    },

    {
      src: theme.urls.worldSprite6,
      x: 675,
      y: 410,
      frame: 12,
      originWidth: 52,
      originHeight: 62,
      width: 80,
      height: 95,
    },

    //LANDMARK
    {
      src: theme.urls.worldSprite3,
      x: 460,
      y: 264,
      frame: 11,
      originWidth: 124.72,
      originHeight: 128,
      width: 125,
      height: 128,
    },
    {
      src: theme.urls.worldSprite5,
      x: 945,
      y: 230,
      frame: 6,
      originWidth: 120.57,
      originHeight: 140,
      width: 120,
      height: 140,
    },
  ];

  return {
    mainBg,
    imageList,
    spriteList,
  };
};

export default useImageData;
